variables:
  IMAGE_NAME: saknouche/todo-app
  IMAGE_TAG: "1.0"

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY vagrant@172.16.96.134 "
      docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD &&
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -d -p 3000:3000 $IMAGE_NAME:$IMAGE_TAG"



